language: python
python:
    - "2.7"
env:
    - DJANGO=1.5.10
    - DJANGO=1.6.7
    - DJANGO=1.7
install:
    - pip install argparse
    - pip install -q Django==$DJANGO
    - pip install -q -r requirements.txt
script: python quicktest.py helpdesk
