# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.network "forwarded_port", guest: 8000, host: 8080

  # SEE MORE: https://www.vagrantup.com/docs/provisioning/puppet_apply.html
  config.vm.provision "puppet"
end
