Vagrant.configure(2) do |config|	

	# ----- provider config
	#config.vm.provider "vmware_fusion"
	config.vm.provider "virtualbox" do |v|
      v.memory = 3072
      v.cpus = 4
      v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
    end

    # ----- OS box config
	#config.vm.box = "hashicorp/precise64"
	config.vm.box = "ubuntu/trusty64"
	#config.vm.box = "debian/jessie64"
	#config.vm.box = "debian/wheezy64"
	config.vm.network "forwarded_port", guest: 80, host: 80
	config.vm.network "forwarded_port", guest: 8080, host: 8080
	config.vm.network "forwarded_port", guest: 8000, host: 8000
	config.vm.network "forwarded_port", guest: 10000, host: 10000
	config.vm.synced_folder "../", "/home/vagrant/repo"
	
	config.ssh.username = "vagrant"
	#config.ssh.username = "root"
	config.ssh.password = "vagrant"
	#config.ssh.insert_key = 'true'
	#sudo passwd root

	# ----- shell provision
    $script = <<-SCRIPT
        sudo apt-get update -y
        sudo apt-get install -y puppet
        sudo puppet apply /home/vagrant/repo/server/manifests/local_tools.pp
        sudo puppet apply /home/vagrant/repo/server/manifests/local_default_server.pp
        sudo puppet apply /home/vagrant/repo/server/manifests/local_default_client.pp
    SCRIPT
    config.vm.provision "shell", inline: $script, privileged: false

	# ----- puppet provision
	#config.vm.provision "puppet" do |puppet|
	#	puppet.manifests_path = "manifests"
	#	puppet.manifest_file  = "local_default.pp"
	#end

end
